"""Codex workflow for fixing Rust `cargo check` failures."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any

from langchain_core.messages import AIMessage
from langchain_codex import ChatCodex

MAX_REVIEW_ATTEMPTS = 3
NIX_CARGO_CHECK_COMMAND = "nix develop -c cargo check"
PREVIEW_MAX_LINES = 8
PREVIEW_MAX_CHARS = 700


def build_cargo_diagnosis_prompt(
    project_path: str,
    cargo_check_output: str,
    extra_constraints: str | None = None,
) -> str:
    """Build the initial diagnosis prompt for a Rust project.

    Args:
        project_path: Path to the Rust workspace or crate.
        cargo_check_output: Captured `cargo check` output.
        extra_constraints: Optional additional constraints for the workflow.

    Returns:
        A prompt that asks Codex to diagnose the failures without running tools.
    """
    constraints = extra_constraints or "No extra constraints."
    return f"""You are helping fix a Rust project based on captured cargo check output.

Project path:
{project_path}

cargo check output:
{cargo_check_output}

Extra constraints:
{constraints}

Inspect the repository directly.
Run commands when needed.
Use nix develop for every Rust command.
If the project does not provide a working flake dev shell, treat that as a blocker and say so explicitly.
When you refer to cargo validation, use: `{NIX_CARGO_CHECK_COMMAND}`.
Do not assume facts that are not present in the project path or cargo check output.

Produce a concise Markdown report with these sections:

1. `Failure summary`
   - Summarize the root causes visible in the cargo check output.

2. `Likely files to inspect`
   - List the files or modules most likely involved.

3. `Fix strategy`
   - Describe a safe order for addressing the failures.

4. `Risks`
   - Call out anything that may need careful review after code changes.
"""


def build_fix_plan_prompt(diagnosis: str) -> str:
    """Build the follow-up prompt that turns diagnosis into a fix plan.

    Args:
        diagnosis: The diagnosis generated by Codex.

    Returns:
        A prompt requesting a phased Markdown fix plan.
    """
    return f"""Turn this cargo failure diagnosis into a phased fix plan.

Diagnosis:
{diagnosis}

Inspect the repository directly.
Run commands when needed.
Use nix develop for every Rust command.
If the project does not provide a working flake dev shell, treat that as a blocker and say so explicitly.
When you refer to cargo validation, use: `{NIX_CARGO_CHECK_COMMAND}`.

Output a concise Markdown plan with:

- a short ordered list of phases
- the goal of each phase
- the files or modules likely to change
- the expected review focus for each phase
"""


def build_step_list_prompt(fix_plan: str) -> str:
    """Ask Codex for a machine-readable step list.

    Args:
        fix_plan: Markdown fix plan produced by Codex.

    Returns:
        A prompt requesting a strict JSON step list.
    """
    return f"""Convert this cargo fix plan into a step list for implementation.

Fix plan:
{fix_plan}

Inspect the repository directly.
Run commands when needed.
Use nix develop for every Rust command.
If the project does not provide a working flake dev shell, treat that as a blocker and say so explicitly.
When you refer to cargo validation, use: `{NIX_CARGO_CHECK_COMMAND}`.
Return valid JSON only.
Use this schema:
{{
  "steps": [
    {{
      "id": "step-1",
      "title": "short title",
      "goal": "one concrete fix goal",
      "files": ["src/lib.rs"],
      "acceptance_criteria": ["specific reviewable outcome"]
    }}
  ]
}}

Rules:
- Return between 1 and 6 steps.
- Keep each step small enough to implement and review independently.
- Prefer steps that resolve compiler errors in a stable order.
"""


def build_step_implementation_prompt(
    project_path: str,
    cargo_check_output: str,
    step: dict[str, Any],
    review_history: list[dict[str, Any]],
) -> str:
    """Build the implementer prompt for a single cargo fix step.

    Args:
        project_path: Path to the Rust workspace or crate.
        cargo_check_output: Captured `cargo check` output.
        step: Structured step data from the step list.
        review_history: Prior review outputs for the step.

    Returns:
        A prompt that asks Codex to implement or revise a single step.
    """
    review_feedback = "No reviewer feedback yet."
    if review_history:
        review_feedback = json.dumps(review_history[-1], indent=2, sort_keys=True)

    return f"""Implement this Rust fix step for the project at:
{project_path}

cargo check output:
{cargo_check_output}

Step:
{json.dumps(step, indent=2, sort_keys=True)}

Most recent reviewer feedback:
{review_feedback}

Inspect the repository directly.
Run commands when needed.
Use nix develop for every Rust command.
If the project does not provide a working flake dev shell, treat that as a blocker and say so explicitly.
When you refer to cargo validation, use: `{NIX_CARGO_CHECK_COMMAND}`.

Instructions:
- Propose the smallest code change that satisfies the step goal.
- If reviewer feedback is present, address those issues first.
- Keep the work scoped to this step.
- End with a brief implementation summary mentioning the files to change and any remaining uncertainty.
"""


def build_step_review_prompt(step: dict[str, Any], implementation_summary: str) -> str:
    """Build the reviewer prompt for one implementation attempt.

    Args:
        step: Structured step data from the step list.
        implementation_summary: The latest implementer summary.

    Returns:
        A prompt that requests a strict JSON review result.
    """
    return f"""Review the latest implementation proposal for this Rust fix step.

Step:
{json.dumps(step, indent=2, sort_keys=True)}

Implementation summary:
{implementation_summary}

Inspect the repository directly.
Run commands when needed.
Use nix develop for every Rust command.
If the project does not provide a working flake dev shell, treat that as a blocker and say so explicitly.
When you refer to cargo validation, use: `{NIX_CARGO_CHECK_COMMAND}`.
Return valid JSON only.
Use this schema:
{{
  "status": "ok",
  "summary": "why the step is acceptable",
  "issues": []
}}

If the step is not acceptable, return:
{{
  "status": "not_ok",
  "summary": "high-level reason",
  "issues": ["specific problem to fix", "another problem if needed"]
}}

Review rules:
- Only return "status": "ok" when the step goal and acceptance criteria are satisfied.
- If the step is not acceptable, explain what is wrong and what should change.
"""


def build_judge_prompt(
    step: dict[str, Any],
    implementation_history: list[str],
    review_history: list[dict[str, Any]],
) -> str:
    """Build the judge prompt after repeated failed reviews.

    Args:
        step: Structured step data from the step list.
        implementation_history: Summaries from implementation attempts.
        review_history: Structured review outputs for the step.

    Returns:
        A prompt that asks for one of three terminal decisions.
    """
    return f"""Three review attempts failed for the same Rust fix step.

Step:
{json.dumps(step, indent=2, sort_keys=True)}

Implementation history:
{json.dumps(implementation_history, indent=2)}

Review history:
{json.dumps(review_history, indent=2, sort_keys=True)}

Inspect the repository directly.
Run commands when needed.
Use nix develop for every Rust command.
If the project does not provide a working flake dev shell, treat that as a blocker and say so explicitly.
When you refer to cargo validation, use: `{NIX_CARGO_CHECK_COMMAND}`.
Return valid JSON only.
Use this schema:
{{
  "decision": "continue_fix",
  "reason": "why another fix attempt is justified"
}}

Allowed decisions:
- "decision": "continue_fix"
- "decision": "continue_next_step"
- "decision": "cancel_all"

Choose exactly one decision.
"""


def _parse_json_response(content: str) -> dict[str, Any]:
    """Parse a JSON object returned by Codex.

    Args:
        content: Raw model response expected to contain one JSON object.

    Returns:
        Parsed JSON object.

    Raises:
        ValueError: If the response is not a JSON object.
    """
    parsed = json.loads(content)
    if not isinstance(parsed, dict):
        msg = "Expected a JSON object response."
        raise ValueError(msg)
    return parsed


def _message_text(message: AIMessage) -> str:
    """Return the text view of a model response.

    Args:
        message: The model response message.

    Returns:
        The plain-text content extracted from the response.
    """
    return str(message.text)


def _truncate_preview(
    text: str,
    *,
    max_lines: int = PREVIEW_MAX_LINES,
    max_chars: int = PREVIEW_MAX_CHARS,
) -> str:
    """Return a compact preview for terminal display."""
    normalized = text.strip()
    if not normalized:
        return "(no output)"

    lines = normalized.splitlines()
    preview = "\n".join(lines[:max_lines]).strip()

    if len(preview) > max_chars:
        return f"{preview[: max_chars - 3].rstrip()}..."
    if len(lines) > max_lines:
        return f"{preview}\n..."
    return preview


def _print_preview(title: str, text: str) -> None:
    """Print a short labeled preview block."""
    print(f"[preview] {title}")
    print(_truncate_preview(text))
    print()


def _summarize_step_results(step_results: list[dict[str, Any]]) -> str:
    """Return a compact step-result summary."""
    if not step_results:
        return "No step results."

    lines: list[str] = []
    for result in step_results:
        step_id = str(result.get("step_id", "unknown-step"))
        outcome = str(result.get("outcome", "unknown"))
        line = f"{step_id}: {outcome}"
        judge_result = result.get("judge_result")
        if isinstance(judge_result, dict):
            decision = judge_result.get("decision")
            if isinstance(decision, str):
                line = f"{line} (judge: {decision})"
        lines.append(line)
    return "\n".join(lines)


def _log_action(actor: str, message: str) -> None:
    """Print a short action log line for the current workflow stage.

    Args:
        actor: Logical actor name such as `system`, `implementer`, or `reviewer`.
        message: Human-readable description of the current action.
    """
    print(f"[{actor}] {message}")


def _read_cargo_check_output_file(project_path: str, path_str: str) -> str:
    """Read captured `cargo check` output, creating it when absent.

    Args:
        project_path: Path to the Rust workspace or crate.
        path_str: Path to a file containing captured `cargo check` output.

    Returns:
        The file contents.

    Raises:
        SystemExit: If the file cannot be created or read.
    """
    path = Path(path_str)
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        _log_action(
            "system",
            f"Missing cargo output file, running {NIX_CARGO_CHECK_COMMAND} in {project_path}",
        )
        try:
            result = subprocess.run(
                ["nix", "develop", "-c", "cargo", "check"],
                cwd=project_path,
                capture_output=True,
                text=True,
                check=False,
            )
        except OSError as err:
            msg = f"Unable to run {NIX_CARGO_CHECK_COMMAND} in {project_path}: {err}"
            raise SystemExit(msg) from err

        output = f"{getattr(result, 'stdout', '')}{getattr(result, 'stderr', '')}"
        try:
            path.write_text(output)
        except OSError as err:
            msg = f"Unable to write cargo check output file {path}: {err}"
            raise SystemExit(msg) from err
        _log_action("system", f"Saved cargo check output to {path}")

    try:
        return path.read_text()
    except OSError as err:
        msg = f"Unable to read cargo check output file {path}: {err}"
        raise SystemExit(msg) from err


def run_step_review_loop(
    model: ChatCodex,
    project_path: str,
    cargo_check_output: str,
    step: dict[str, Any],
) -> dict[str, Any]:
    """Run the implement-review-judge loop for a single cargo fix step.

    Args:
        model: ChatCodex instance with a persistent thread.
        project_path: Path to the Rust workspace or crate.
        cargo_check_output: Captured `cargo check` output.
        step: Structured step data from the generated step list.

    Returns:
        Structured result for the step outcome.
    """
    implementation_history: list[str] = []
    review_history: list[dict[str, Any]] = []

    while True:
        review_attempts = 0
        while review_attempts < MAX_REVIEW_ATTEMPTS:
            _log_action(
                "implementer",
                f"Running implementer for {step['id']} (attempt {review_attempts + 1})",
            )
            implementation_summary = _message_text(
                model.invoke(
                    build_step_implementation_prompt(
                        project_path,
                        cargo_check_output,
                        step,
                        review_history,
                    )
                )
            )
            implementation_history.append(implementation_summary)
            _print_preview(f"{step['id']} implementer", implementation_summary)

            _log_action(
                "reviewer",
                f"Running reviewer for {step['id']} (attempt {review_attempts + 1})",
            )
            review_result = _parse_json_response(
                _message_text(
                    model.invoke(build_step_review_prompt(step, implementation_summary))
                )
            )
            review_history.append(review_result)
            _print_preview(
                f"{step['id']} reviewer",
                json.dumps(review_result, indent=2, sort_keys=True),
            )

            if review_result.get("status") == "ok":
                _log_action("reviewer", f"{step['id']} accepted")
                return {
                    "step_id": step["id"],
                    "outcome": "ok",
                    "implementation_history": implementation_history,
                    "review_history": review_history,
                }

            _log_action("reviewer", f"{step['id']} requires changes")
            review_attempts += 1

        _log_action("judge", f"Running judge for {step['id']}")
        judge_result = _parse_json_response(
            _message_text(
                model.invoke(
                    build_judge_prompt(step, implementation_history, review_history)
                )
            )
        )
        _print_preview(
            f"{step['id']} judge",
            json.dumps(judge_result, indent=2, sort_keys=True),
        )
        decision = judge_result.get("decision")
        _log_action("judge", f"Judge decision for {step['id']}: {decision}")

        if decision == "continue_fix":
            review_history.append(
                {
                    "status": "not_ok",
                    "summary": "Judge requested another fix cycle.",
                    "issues": [judge_result.get("reason", "No reason provided.")],
                }
            )
            continue

        if decision == "continue_next_step":
            return {
                "step_id": step["id"],
                "outcome": "continue_next_step",
                "judge_result": judge_result,
                "implementation_history": implementation_history,
                "review_history": review_history,
            }

        if decision == "cancel_all":
            return {
                "step_id": step["id"],
                "outcome": "cancel_all",
                "judge_result": judge_result,
                "implementation_history": implementation_history,
                "review_history": review_history,
            }

        msg = f"Unexpected judge decision: {decision!r}"
        raise ValueError(msg)


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the example.

    Returns:
        Parsed arguments.
    """
    parser = argparse.ArgumentParser(
        description="Codex cargo fix loop example."
    )
    parser.add_argument(
        "--project-path",
        required=True,
        help="Path to the Rust project that will be fixed manually or by another tool.",
    )
    parser.add_argument(
        "--cargo-check-output-file",
        required=True,
        help="Path to a file containing captured cargo check output.",
    )
    parser.add_argument(
        "--constraints",
        default=None,
        help="Optional extra constraints to include in the prompts.",
    )
    return parser.parse_args()


def main() -> None:
    """Run the prompt-only cargo fix workflow."""
    args = _parse_args()
    cargo_check_output = _read_cargo_check_output_file(
        args.project_path,
        args.cargo_check_output_file,
    )

    model = ChatCodex(
        model="gpt-5.4",
        launch_command=("ai-creds", "run", "codex", "app-server"),
        approval_policy="never",
        sandbox_policy={"type": "dangerFullAccess"},
    )
    try:
        _log_action("system", "Starting cargo diagnosis")
        diagnosis = model.invoke(
            build_cargo_diagnosis_prompt(
                args.project_path,
                cargo_check_output,
                args.constraints,
            )
        )
        _print_preview("cargo diagnosis", _message_text(diagnosis))
        _log_action("system", "Building cargo fix plan")
        fix_plan = model.invoke(build_fix_plan_prompt(_message_text(diagnosis)))
        _print_preview("cargo fix plan", _message_text(fix_plan))
        _log_action("system", "Building step list")
        step_plan = _parse_json_response(
            _message_text(model.invoke(build_step_list_prompt(_message_text(fix_plan))))
        )
        _print_preview("cargo step plan", json.dumps(step_plan, indent=2, sort_keys=True))

        step_results: list[dict[str, Any]] = []
        for step in step_plan["steps"]:
            _log_action("system", f"Starting step {step['id']}")
            result = run_step_review_loop(
                model,
                args.project_path,
                cargo_check_output,
                step,
            )
            step_results.append(result)
            if result["outcome"] == "cancel_all":
                _log_action("system", f"Stopping after {step['id']} due to cancel_all")
                break
    except (OSError, RuntimeError, ValueError, KeyError, TypeError) as err:
        raise SystemExit(f"Codex cargo example failed: {err}") from err

    print("# Cargo Diagnosis")
    print()
    print(_truncate_preview(_message_text(diagnosis)))
    print()
    print("# Cargo Fix Plan")
    print()
    print(_truncate_preview(_message_text(fix_plan)))
    print()
    print("# Cargo Step Execution Results")
    print()
    print(_summarize_step_results(step_results))


if __name__ == "__main__":
    main()
